version: 2

sources:
  - name: csv_google
    tables:
      - name: fact_original
        config:
          external_location: "read_csv('./gdrive/fact.csv')"
      - name: sm2_01
        config:
          external_location: "read_csv('./gdrive/sm2_01.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_02
        config:
          external_location: "read_csv('./gdrive/sm2_02.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_03
        config:
          external_location: "read_csv('./gdrive/sm2_03.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_04
        config:
          external_location: "read_csv('./gdrive/sm2_04.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_05
        config:
          external_location: "read_csv('./gdrive/sm2_05.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_06
        config:
          external_location: "read_csv('./gdrive/sm2_06.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_07
        config:
          external_location: "read_csv('./gdrive/sm2_07.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_08
        config:
          external_location: "read_csv('./gdrive/sm2_08.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"
      - name: sm2_09
        config:
          external_location: "read_csv('./gdrive/sm2_09.csv', types={
          'venkov': 'text', 'sani': 'text', 'odvod': 'text', 'privod': 'text', 'vyfuk': 'text'
          })"

models:
  - name: fact
    description: the fact table
    columns:
      - name: time
        description: This is a date time
        tests:
          - not_null
