version: 2

sources:
  - name: csv_google
    loaded_at_field: cast(Date as timestamp)

    freshness:
      warn_after: {count: 365, period: day}

    tables:
      - name: fact_original
        freshness:
        config:
          external_location: "read_csv('./gdrive/fact.csv')"
      - name: merged
        config:
          external_location: "read_csv('./gdrive/merged.csv')"